example:
  property: I AM IN THE DEFAULT AS being

redis:
  server: redis
  port: 6379
signing:
  key: 345345fsdfsf5345

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/luz
    username: root
    password: beinglee
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

